Improved telemetry to send all changes to Nuvla and reduce the chance of a "split brain" like scenario.
nuvlabox/agent pull request #101
Opened 2021-11-26 08:43 UTC by schaubl

2021-11-26 17:09 UTC, cjdcordeiro requested changes

2021-11-26 17:09 UTC, cjdcordeiro commented on code/app.py
>                  'status': status.get('status', 'DEGRADED')
when the telemetry falls behind twice in a row, this 'status' field keeps flipping between operational and degraded

2021-11-28 18:52 UTC, schaubl commented on code/agent/Telemetry.py
>          self.status_delete_attrs_in_nuvla = []
They are used by the two corresponding properties

2021-11-28 20:02 UTC, schaubl commented on code/app.py
>                  'status': status.get('status', 'DEGRADED')
I added back the two
```python
nb_telemetry.status.update(status)```

2021-11-28 20:53 UTC, schaubl commented on code/agent/Telemetry.py
> +    def status_on_nuvla(self):
This is just a simple property (with a setter and a getter), it's transparent and quite self explanatory.
It is used in the exact same way as the initial variable with the same name.
I don't think there is a need for an extra docstring.

2021-11-29 10:02 UTC, cjdcordeiro commented on code/agent/Telemetry.py
>          self.status_delete_attrs_in_nuvla = []
the `status_delete_attrs_in_nuvla`

2021-11-29 10:04 UTC, cjdcordeiro commented on code/agent/Telemetry.py
> +        logging.debug(f'{self.name} set {key} = {value}')
why didn't it complain?

2021-11-29 10:12 UTC, schaubl commented on code/agent/Telemetry.py
> +        logging.debug(f'{self.name} set {key} = {value}')
don't know

2021-11-29 10:20 UTC, cjdcordeiro requested changes

2021-11-29 10:20 UTC, cjdcordeiro commented on code/app.py
>                  'status': status.get('status', 'DEGRADED')
this doesn't solve it:
```
agent_1            | INFO:root:Refresh status: {'status-notes': ['NuvlaBox telemetry is falling behind'], 'status': 'DEGRADED'}
agent_1            | INFO:root:Found VPN credential ID credential/09ffa0ca-49a7-415a-b22c-419e11382179
agent_1            | WARNING:root:Telemetry thread not completed in time
agent_1            | INFO:root:Refresh status: {'status-notes': ['NuvlaBox telemetry is falling behind'], 'status': 'DEGRADED'}
agent_1            | INFO:root:Watching VPN credential in Nuvla...
agent_1            | INFO:root:Found VPN credential ID credential/09ffa0ca-49a7-415a-b22c-419e11382179
agent_1            | WARNING:root:Telemetry thread not completed in time
agent_1            | INFO:root:Refresh status: {'status-notes': ['NuvlaBox telemetry is falling behind'], 'status': 'OPERATIONAL'}
agent_1            | WARNING:root:Telemetry thread not completed in time
agent_1            | INFO:root:Refresh status: {'status-notes': ['NuvlaBox telemetry is falling behind'], 'status': 'DEGRADED'}
agent_1            | INFO:root:Watching VPN credential in Nuvla...
```

2021-11-29 10:20 UTC, cjdcordeiro commented on code/app.py
>                  'status': status.get('status', 'DEGRADED')
it happens because the status is being written while that check is ongoing, but not finished yet. So maybe it should simply be forced to DEGRADED always.

2021-11-29 11:13 UTC, schaubl commented on code/app.py
>                  'status': status.get('status', 'DEGRADED')
Humm .... I will have a look.

2021-11-29 16:36 UTC, merged