make logging level configurable
nuvlabox/agent pull request #104
Opened 2022-01-17 15:59 UTC by cjdcordeiro

closes https://github.com/nuvlabox/deployment/issues/71

2022-01-18 15:22 UTC, schaubl requested changes
This new code should go in the "main" function.
This is a best practice so that if another code import this file (for example to test it), the logging configuration will not be overwritten.

To keep it on top of the file you can simply put it in a 
```python
if __name__ == "__main__":
```
but I think it's not needed.
I would put it in a function and call it at the beginning of the existing "main".

2022-01-18 15:27 UTC, cjdcordeiro commented
that's true, but the problem with that is that some modules will perform actions at import time, so if this is not executed first thing in the code, those imports will not have DEBUG set

2022-01-18 16:13 UTC, schaubl commented
> that's true, but the problem with that is that some modules will perform actions at import time, so if this is not executed first thing in the code, those imports will not have DEBUG set

They should not but if they do, you can do what I mentioned above, just wrap the code with
```python
if __name__ == "__main__":
```
and keeping it at the top.

which give the following (I refactored it a bit):
```python
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="NuvlaBox Agent")
    parser.add_argument('--debug', dest='debug', default=False, action='store_true',
                        help='use for increasing the verbosity level')
    
    level = logging.INFO

    if parser.parse_args().debug:
        level = logging.DEBUG
    else:
        try:
            level = logging.getLevelName(os.getenv('NUVLABOX_LOG_LEVEL'))
        except ValueError:
            pass

    logging.basicConfig(stream=sys.stdout, level=level)
```

Maybe, first give a try to see if it makes a difference if the code is at the top of the file or inside the existing "main".

2022-02-01 16:22 UTC, schaubl approved these changes

2022-02-01 16:23 UTC, merged