Network report issue#85
nuvlabox/agent pull request #109
Opened 2022-03-16 08:56 UTC by ignacio-penas

2022-03-17 07:31 UTC, konstan commented
@ignacio-penas Couple of generic things. Please provide a description (what is the intent, and what was done), link an issue this PR is related to (if any). Set Project, and Labels (if any). 
Also, the SonarCloud Quality Gate failed. Are you working on resolving this or what is your strategy regarding the failure?

2022-03-23 14:32 UTC, konstan commented on code/agent/monitor/components/network_interface_monitor.py
> +        except errors.NotFound as imageNotFound:
Rename to `ex`.

... and others below.

2022-03-24 11:50 UTC, konstan commented on code/agent/monitor/components/network_interface_monitor.py
> +from docker import errors
sure :) `docker_err.NotFound` is just shorter. No other reason.

2022-03-24 11:52 UTC, ignacio-penas commented on code/agent/monitor/components/network_interface_monitor.py
> +    def get_data(self):
None value is fine. It will just leave the report field for IP empty.

2022-03-24 11:53 UTC, konstan requested changes

2022-03-24 11:53 UTC, konstan commented on code/tests/monitor/test_network_interface_monitor.py
> +        # test_ip_monitor.data = Mock()
@ignacio-penas Is this needed? if so, please provide a comment why - otherwise, delete the line.

2022-03-24 11:53 UTC, ignacio-penas commented on code/agent/monitor/components/network_interface_monitor.py
> +from docker import errors
I have just updated it with 'docker_err'

2022-03-24 11:58 UTC, ignacio-penas commented on code/tests/monitor/test_network_interface_monitor.py
> +        # test_ip_monitor.data = Mock()
Done

2022-03-24 12:33 UTC, konstan approved these changes

2022-03-24 13:12 UTC, konstan commented
@schaubl I'm done with the review. I also merged master.  Please review/merge.

2022-04-27 09:04 UTC, schaubl commented
This has been merged into nuvlabox/agent#114. Closing

2022-04-27 09:04 UTC, schaubl commented
This has been merged into nuvlabox/agent#114. Closing

2022-04-27 09:04 UTC, closed without merging